### ISSUE TITLE
Nice work！Is this part for loading pretrained VGG model?And it is a way to initialize the layer's weight?

### ISSUE THREAD

**Issue by jackfrost168** [ZhengPeng7/W-Net-Keras#2]
`front_end = VGG16(weights='imagenet', include_top=False)`
`weights_front_end = []`
    `for layer in front_end.layers:`
       ` if 'conv' in layer.name:`
            `weights_front_end.append(layer.get_weights())`
   ` counter_conv = 0`
    `for i in range(len(model.layers)):`
       ` if counter_conv >= 13:`
           ` break`
        `if 'conv' in model.layers[i].name:`
            `model.layers[i].set_weights(weights_front_end[counter_conv])`
            `counter_conv += 1`

**Comment by ZhengPeng7** [comment]
Thank you, though it's only an uncomplete work which may differ from the original paper in some details.

You're right, this part is used for loading the pre-trained VGG backbone. I think writing in this way is more flexible for network construction in this work than using something like this in official tutorial:
`base_model = VGG19(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('block4_pool').output)
...`.

**Comment by jackfrost168** [comment]
Thank you for your replying!
