### ISSUE TITLE
When generating the dataset an Error occurs:  ValueError: operands could not be broadcast together with shapes (568,15) (0,15) (568,15) 

### ISSUE THREAD

**Issue by Prosat** [ZhengPeng7/W-Net-Keras#3]
data/ShanghaiTech/part_A/train_data\images\IMG_118.jpg
  4%|▍         | 21/482 [00:02<00:45, 10.16it/s]
Traceback (most recent call last):
  File "C:/Users/a/PycharmProjects/W-Net-Keras/generate_datasets.py", line 46, in <module>
    DM = gen_density_map_gaussian(k, gt, sigma=sigma)
  File "C:\Users\a\PycharmProjects\W-Net-Keras\utils_gen.py", line 86, in gen_density_map_gaussian
    ] += gaussian_map
ValueError: operands could not be broadcast together with shapes (568,15) (0,15) (568,15) 

The same problem occurs in your other code, SANet-Keras. I'm using Python 3.7.

**Comment by wentixiaogege** [comment]
if (gaussian_map.shape[1] ==0)or(gaussian_map.shape[0]==0):
            continue

**Comment by wentixiaogege** [comment]
redefine below function 

def gen_density_map_gaussian(im, points, sigma=4):
    """
    func: generate the density map
    """
    density_map = np.zeros(im.shape[:2], dtype=np.float32)
    h, w = density_map.shape[:2]
    num_gt = np.squeeze(points).shape[0]
    if num_gt == 0:
        return density_map
    for p in points:
        p = np.round(p).astype(int)
        p[0], p[1] = min(h-1, p[1]), min(w-1, p[0])
        gaussian_radius = sigma * 2 - 1
        gaussian_map = np.multiply(
            cv2.getGaussianKernel(int(gaussian_radius*2+1), sigma),
            cv2.getGaussianKernel(int(gaussian_radius*2+1), sigma).T
        )
        x_left, x_right, y_up, y_down = 0, gaussian_map.shape[1], 0, gaussian_map.shape[0]
        # cut the gaussian kernel
        if p[1] < gaussian_radius:
            x_left = gaussian_radius - p[1]
        if p[0] < gaussian_radius:
            y_up = gaussian_radius - p[0]
        if p[1] + gaussian_radius >= w:
            x_right = gaussian_map.shape[1] - (gaussian_radius + p[1] - w) - 1
        if p[0] + gaussian_radius >= h:
            y_down = gaussian_map.shape[0] - (gaussian_radius + p[0] - h) - 1
        gaussian_map = gaussian_map[y_up:y_down, x_left:x_right]
        if np.sum(gaussian_map):
            gaussian_map = gaussian_map / np.sum(gaussian_map)
#         print('ljj checking here ',gaussian_map.shape,density_map.shape)
        if (gaussian_map.shape[1] ==0)or(gaussian_map.shape[0]==0):
            continue
        density_map[
            max(0, p[0]-gaussian_radius):min(h, p[0]+gaussian_radius+1),
            max(0, p[1]-gaussian_radius):min(w, p[1]+gaussian_radius+1)
        ] += gaussian_map
    density_map = density_map / (np.sum(density_map / num_gt))
    return density_map

**Comment by ZhengPeng7** [comment]
Sorry for the late reply, I remember this problem was caused by the negative axis values in SH dataset. You should notice that there are two versions of SH dataset A and B, one link is to dropbox, another one is to Baidu Disk. I used the one from dropbox since there are negative ones in that from Baidu Disk which actually shouldn't exist.

**Comment by wentixiaogege** [comment]
but the dropbox sharing is cancelled ? can u update the baidu pan data；

for now  my results on the baidu pan

 73.45434 118.59023 0.010220066 0.18018237 23.290236517822745 0.6487061596273813

with same configuration , seems not acceptable~

thanks in advance~

**Comment by ZhengPeng7** [comment]
Thanks for your interest. The link was copied from an MCNN repository, and it's true that it doesn't work now. But I'm really busy with exams recently, and this W-Net is an uncomplete version, I remember that there're some points not clear in the original paper, and I spent time on other things at that time.

And it's very very similar to **SFANet**, the whole network _architecture_, and almost every _hyperparameter_ and the  SFANet is _earlier_ than W-Net on arXiv. If you need this network architecture for your research, I recommend [this SFANet reproduction](https://github.com/pxq0312/SFANet-crowd-counting) for you.

Good luck.
