### ISSUE TITLE
Dataset isn't accessibly

### ISSUE THREAD

**Issue by dimka11** [ZhengPeng7/W-Net-Keras#5]
I can't download dataset from dropbox neither baidu.

**Comment by ZhengPeng7** [comment]
Some of the official links have broken. You can download them from [my personal google-drive](https://drive.google.com/drive/folders/1TGbjYyMhFDJAK3jGCy3yPY6pLq87ebeN?usp=sharing)

**Comment by dimka11** [comment]
Thanks
